import Header from '@/components/headers/Headers';
import '../globals.css';
import FooterSection from '@/components/Footer';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen flex flex-col">
          <Header />
          {/* <BlogBanner /> */}
          {/* Main content */}
          {children}
          {/* Footer or additional content can go here */}
          <FooterSection />
        </div>
      </body>
    </html>
  );
}
